import { SharedReelView } from "@/components/dashboard/Studio/SharedReelView";

export default function GalleryPage() {
          return (
                    <SharedReelView
                              title="Community Gallery"
                              description="Explore trending, viral, and highly engaging faceless reels generated by other creators."
                              pageType="gallery"
                    />
          );
}