[build]
  command = "npm install && cd apps/auth-service && npx prisma generate --schema=../../packages/database/prisma/schema.prisma && next build"
  publish = "apps/auth-service/.next"

[build.environment]
  NODE_VERSION = "20"
  NODE_ENV = "development"